version: "3.8"

services:

  php-apache:
    build:
      args:
        - WWW_USER_ID=${WWW_USER_ID}
        - WWW_GROUP_ID=${WWW_GROUP_ID}
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ${PROJECT_PATH_HOST}:/var/www/html
